### ISSUE TITLE
How to Install / Use?

### ISSUE THREAD

**Issue by Countryen** [ElektroStudios/SharpShell-Easy-Log#1]
Hey there,

lovely tool you created ♥

Just a simple thing - how Do I use/download the tool? 
I couldn't find a download / release link and don't want to clone/download the repo just for use.

Maybe you want to add a Nuget-Package as well ;) ?

Cheers

**Comment by ElektroStudios** [comment]
Sorry I just missed to publish the release package when I commited the initial release, here is:

 - https://github.com/ElektroStudios/SharpShell-Easy-Log/releases/latest

I'm not planning to upload this at NuGet.

Thanks for comment!.

**Comment by Countryen** [comment]
Great, thanks.
